# Generated by Django 5.2.5 on 2025-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_follow_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=600),
        ),
    ]
